name: Manual Pipeline (Turborepo)

on:
  # Ativa apenas o gatilho manual
  workflow_dispatch:
    inputs:
      project:
        description: 'Projeto para rodar (ex: shell, mfe-remote ou deixe vazio para TUDO)'
        required: false
        default: ''
        type: string

jobs:
  build:
    name: Build & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # fetch-depth: 0 garante que o Turbo consiga comparar 
          # histórico se você usar filtros de diff
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Turbo
        run: |
          # Verifica se um projeto específico foi solicitado
          if [ "${{ github.event.inputs.project }}" != "" ]; then
            echo "Executando build para o projeto: ${{ github.event.inputs.project }}"
            npx turbo run build --filter=${{ github.event.inputs.project }}
          else
            echo "Executando build para TODOS os projetos no monorepo"
            npx turbo run build
          fi